### ISSUE TITLE
Use React Helmet to manage changes to the document head

### ISSUE THREAD

**Issue by CloudPower97** [Educabile/EducabileWeb#28]
Use [React Helmet](https://github.com/nfl/react-helmet) to:
- [ ] Add different title to every page
- [ ] Add different keywords to every page
- [ ] Add different description to every page
For blog posts:
     - [ ] Use the excerpt returned by WP
- [ ] Use `<meta name="theme-color" content="#color">`
Where #color is to be added dynamically for these section with these matching colors:
     - [ ] For blog posts regarding `Didattica Digitale` color should be `#FF9800`
     - [ ] For blog posts regarding `Data Technology` color should be `#4CAF50`
     - [ ] For blog posts regardin `Internet Of Things` color should be `#9C27B0`
     - [ ] For any other things color should be `#1565C0`
